info:
  version: @project.version@
server:
  port: 8080
spring:
  application:
     name: springboot-auth
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.32.140:3306/springbootdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
  redis:
    host: 127.0.0.1
    database: 0
  #  password: grape
  jpa:
     hibernate:
         ddl-auto: update
         naming:
           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     show-sql: true
eureka:
  instance:
    hostname: 192.168.32.140
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://192.168.32.140:8761/eureka/    # 指定注册中心的地址
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false ,否则很多点监控不到

